[build]
  command = "cd face-a-phrase && npm i && npm run build"
  publish = "face-a-phrase/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


